### ISSUE TITLE
additional shortcuts needed in presentation mode

### ISSUE THREAD

**Issue by bhempel** [yCanta/yCanta#30]
(1) When projecting a song in presentation mode, hitting "2" serves as a shortcut to display verse 2, hitting "c" serves as a shortcut to display the chorus, etc.  Shortcuts are needed for songs like Above All Powers which do not have verses or choruses, but just several "nolabel" stanzas.  I think that, for such songs, "1" should shortcut to the 1st stanza, "2" should shortcut to the 2nd stanza, etc.  Another very good example song is We Bow Down, which has 4 chunks, 2 that are nolabel and 2 that are indented-nolabel.

(2) "c" shortcuts to the chorus, unless there is a pre-chorus, in which case it sends you there.  This seems wrong to me.  I think there should be a way to go to whatever song chunk you want to.  Please check that there is a way to do that.  I don't think that you can use "p" to shortcut to the pre-chorus because "p" is used for "presentation mode" and gives you a list of the songs in the database.  (In a similar vein, are there shortcuts for "bridge", "final chorus", and "ending"?)

The above requests came from Casey who controls the projector on Sunday mornings.

**Comment by carlhemp** [comment]
1) This makes a lot of sense.  This shouldn't be too hard to add.
2) Bridge and Ending have shortcuts "b" and "e" respectively(you can check all bindings when you open the presentation).  Oftentimes I won't know if there is a pre-chorus, and so making the c key take you to the pre-chorus prevents that possibility.  It could be possible to make pre and final chorus have their own keys though it would require some shuffling of key assignments.  I'd prefer to use the "c" key and possibly add some intelligence so that if it's pressed again it moves to the next "chorus" type chunk...  If there are other ideas on how to make it work better, I'd love to hear them too.

**Comment by evanhempel** [comment]
Fixed both items.  For the 2nd one (choruses), the c key now goes to the next chunk of type chorus, pre-chorus, or final chorus.  If there is no next type then it wraps to the beginning of the song and looks for a chorus.
